import { LearningResource } from '../../src/types/index.ts';

export const CURATED_LEARNING_RESOURCES: LearningResource[] = [
  // --- PYTHON ---
  {
    id: 'res_py_cs50p',
    title: "Harvard CS50P: CS50's Introduction to Programming with Python",
    subject: 'Python',
    type: 'free_course',
    provider: 'Harvard CS50',
    url: 'https://cs50.harvard.edu/python/',
    embedUrl: 'https://www.youtube.com/embed/nLRL_NcnK-4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=500&auto=format&fit=crop&q=80',
    duration: '10-week Full Course (16h)',
    difficulty: 'Beginner',
    description: "An introduction to programming using Python, taught by Prof. David J. Malan at Harvard. Covers functions, variables, conditionals, loops, exceptions, libraries, unit tests, file I/O, regex, and OOP.",
    keyTopics: ['Functions & Variables', 'Conditionals & Loops', 'Exceptions', 'File I/O', 'Regex', 'Object-Oriented Programming'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_py_fcc_full',
    title: 'Python for Beginners – Full Course [Programming with Mosh]',
    subject: 'Python',
    type: 'youtube_video',
    provider: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
    embedUrl: 'https://www.youtube.com/embed/_uQrJ0TkZlc',
    thumbnailUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=500&auto=format&fit=crop&q=80',
    duration: '6 Hours',
    difficulty: 'Beginner',
    description: 'Learn Python programming in this complete course for beginners. Covers foundational syntax, lists, tuples, dictionaries, functions, classes, and building 3 real-world projects.',
    keyTopics: ['Syntax Fundamentals', 'Lists & Tuples', 'Dictionaries', 'Classes & Modules', 'Automation Projects'],
    isFreeVerified: true,
  },
  {
    id: 'res_py_corey_oop',
    title: 'Python OOP Tutorials – Classes and Object Oriented Programming',
    subject: 'Python',
    type: 'youtube_playlist',
    provider: 'Corey Schafer',
    url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc',
    embedUrl: 'https://www.youtube.com/embed/ZDa-Z5JzLYM',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500&auto=format&fit=crop&q=80',
    duration: '6 Videos (2.5 Hours)',
    difficulty: 'Intermediate',
    description: 'The premier tutorial series on Python Object-Oriented Programming by Corey Schafer. Master class instances, class variables, regular methods, classmethods, staticmethods, inheritance, and dunder magic methods.',
    keyTopics: ['Classes & Instances', 'Class vs Instance Variables', 'Classmethods & Staticmethods', 'Inheritance & Subclasses', 'Special (Dunder) Methods', 'Property Decorators'],
    isFreeVerified: true,
  },

  // --- JAVA ---
  {
    id: 'res_java_kunal',
    title: 'Java + DSA + Interview Preparation Bootcamp',
    subject: 'Java',
    type: 'youtube_playlist',
    provider: 'Kunal Kushwaha',
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ',
    embedUrl: 'https://www.youtube.com/embed/wn49bRJ8Ggk',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&auto=format&fit=crop&q=80',
    duration: '60+ In-Depth Lectures (50h)',
    difficulty: 'All Levels',
    description: 'A comprehensive, zero-to-hero Java programming and Data Structures & Algorithms course taught by Kunal Kushwaha. Covers Java internals, memory management, OOP, recursion, trees, graphs, and dynamic programming.',
    keyTopics: ['Java Syntax & Memory Model', 'OOP Concepts & Packages', 'Recursion & Backtracking', 'Sorting Algorithms', 'Trees & Graphs', 'System Design Basics'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_java_brocode',
    title: 'Java Full Course for Beginners [12 Hours]',
    subject: 'Java',
    type: 'youtube_video',
    provider: 'Bro Code',
    url: 'https://www.youtube.com/watch?v=xk4_1vDrzzo',
    embedUrl: 'https://www.youtube.com/embed/xk4_1vDrzzo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579468118864-ddb621292981?w=500&auto=format&fit=crop&q=80',
    duration: '12 Hours',
    difficulty: 'Beginner',
    description: 'Complete Java course from scratch. Covers variables, data types, math, if statements, switches, logical operators, loops, arrays, OOP, inheritance, abstraction, interfaces, polymorphism, file handling, and audio players.',
    keyTopics: ['Java Basics', 'Array Manipulation', 'OOP & Constructors', 'Interfaces & Abstract Classes', 'Exception Handling', 'GUI & Audio'],
    isFreeVerified: true,
  },
  {
    id: 'res_java_mooc',
    title: 'University of Helsinki: Java Programming I & II (MOOC.fi)',
    subject: 'Java',
    type: 'free_course',
    provider: 'University of Helsinki',
    url: 'https://java-programming.mooc.fi/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
    duration: '14-week University Course',
    difficulty: 'Beginner',
    description: 'Renowned online course with hundreds of automated exercises tested in the TMC environment. Master clean Java code, algorithmic thinking, unit testing, and design patterns.',
    keyTopics: ['Procedural Programming', 'Object-Oriented Design', 'Collections & HashMaps', 'Automated Unit Testing', 'File Processing', 'Streams & Lambdas'],
    isFreeVerified: true,
  },

  // --- C PROGRAMMING ---
  {
    id: 'res_c_fcc',
    title: 'C Programming Tutorial for Beginners [freeCodeCamp]',
    subject: 'C',
    type: 'youtube_video',
    provider: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=KJgsSFOSQv0',
    embedUrl: 'https://www.youtube.com/embed/KJgsSFOSQv0',
    thumbnailUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=500&auto=format&fit=crop&q=80',
    duration: '3.5 Hours',
    difficulty: 'Beginner',
    description: 'Learn C programming from Mike Dane. Covers installation, variables, data types, printf/scanf, arrays, functions, pointers, memory addresses, and file operations.',
    keyTopics: ['Variables & Data Types', 'Pointers & Memory Addresses', 'Arrays & 2D Arrays', 'Structs', 'Reading & Writing Files'],
    isFreeVerified: true,
  },
  {
    id: 'res_c_cs50x',
    title: "Harvard CS50x: C Programming & Low-Level Memory Mastery",
    subject: 'C',
    type: 'free_course',
    provider: 'Harvard CS50',
    url: 'https://cs50.harvard.edu/x/',
    embedUrl: 'https://www.youtube.com/embed/8mAITcNt710',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=80',
    duration: 'Weeks 1–5 (20 Hours)',
    difficulty: 'Intermediate',
    description: 'Harvard University flagship course. Deep dive into C syntax, manual memory allocation with malloc and free, pointer manipulation, and implementing linked lists, hash tables, and tries from scratch.',
    keyTopics: ['C Syntax & Types', 'Compilation Pipeline (clang)', 'Pointers & Dereferencing', 'Dynamic Memory & Valgrind', 'Linked Lists & Trees'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_c_abdul_bari',
    title: 'Pointers in C – The Complete Masterclass [Abdul Bari]',
    subject: 'C',
    type: 'youtube_playlist',
    provider: 'Abdul Bari',
    url: 'https://www.youtube.com/playlist?list=PLGLfVvz_LVvSrS7R4W5020ukaQnnCwupZ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=500&auto=format&fit=crop&q=80',
    duration: '15 Videos (4 Hours)',
    difficulty: 'Intermediate',
    description: 'Renowned computer science educator Abdul Bari breaks down pointer arithmetic, double pointers, pointer to array, function pointers, and memory layout with intuitive blackboard visualizations.',
    keyTopics: ['Pointer Syntax & Dereferencing', 'Pointer Arithmetic', 'Pointers to Arrays & Strings', 'Function Pointers', 'Dynamic Heap Allocation'],
    isFreeVerified: true,
  },

  // --- C++ ---
  {
    id: 'res_cpp_cherno',
    title: 'The C++ Series – Master Modern C++ [The Cherno]',
    subject: 'C++',
    type: 'youtube_playlist',
    provider: 'The Cherno',
    url: 'https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4G5b',
    embedUrl: 'https://www.youtube.com/embed/18c3MTX0PK0',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&auto=format&fit=crop&q=80',
    duration: '100+ Videos (35 Hours)',
    difficulty: 'All Levels',
    description: 'Game engine architect Yan Chernikov (The Cherno) explains how C++ works under the hood. Covers pointers, references, classes, virtual functions, templates, smart pointers, dynamic memory, and modern C++ features.',
    keyTopics: ['How C++ Works & Linkers', 'Pointers vs References', 'Virtual Functions & vtables', 'Smart Pointers (unique/shared)', 'Templates & Metaprogramming', 'Move Semantics & std::move'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_cpp_fcc_full',
    title: 'C++ Programming Course – Beginner to Advanced [31 Hours]',
    subject: 'C++',
    type: 'youtube_video',
    provider: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=8jLOx1hD3_o',
    embedUrl: 'https://www.youtube.com/embed/8jLOx1hD3_o',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=500&auto=format&fit=crop&q=80',
    duration: '31 Hours',
    difficulty: 'Intermediate',
    description: 'Massive full C++ 20 curriculum. Comprehensive deep dive from basic syntax up to concepts, modules, templates, smart pointers, lambda functions, and STL algorithms.',
    keyTopics: ['C++20 Fundamentals', 'Pointers & References', 'Object Oriented C++', 'Templates & Concepts', 'STL Containers & Iterators', 'Smart Pointers & RAII'],
    isFreeVerified: true,
  },

  // --- C# ---
  {
    id: 'res_csharp_fcc',
    title: 'C# Full Course for Beginners [freeCodeCamp]',
    subject: 'C#',
    type: 'youtube_video',
    provider: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=GhQdlIFylQ8',
    embedUrl: 'https://www.youtube.com/embed/GhQdlIFylQ8',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&auto=format&fit=crop&q=80',
    duration: '4.5 Hours',
    difficulty: 'Beginner',
    description: 'Learn C# fundamentals with Mike Dane. Covers variables, data types, strings, numbers, user input, arrays, methods, conditionals, switches, loops, classes, objects, and getters & setters.',
    keyTopics: ['C# Syntax & Types', 'Methods & Return Types', 'Arrays & Collections', 'Classes & Objects', 'Constructors & Access Modifiers'],
    isFreeVerified: true,
  },
  {
    id: 'res_csharp_mslearn',
    title: 'Foundational C# Certification [freeCodeCamp & Microsoft Learn]',
    subject: 'C#',
    type: 'free_course',
    provider: 'freeCodeCamp & Microsoft',
    url: 'https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500&auto=format&fit=crop&q=80',
    duration: '35 Hours (Interactive)',
    difficulty: 'All Levels',
    description: 'Official comprehensive C# learning pathway certified jointly by Microsoft and freeCodeCamp. Learn write your first C# code, work with variable data, logic branches, and build applications with .NET.',
    keyTopics: ['Console Applications', 'Variables & Data Types', 'Branching Logic & Loops', 'Array & Collection Operations', 'Debugging & Exception Handling', 'Readable Clean Code'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_csharp_mosh',
    title: 'C# Tutorial for Beginners: Learn C# in 1 Hour [Programming with Mosh]',
    subject: 'C#',
    type: 'youtube_video',
    provider: 'Programming with Mosh',
    url: 'https://www.youtube.com/watch?v=gfkTfcpWqAY',
    embedUrl: 'https://www.youtube.com/embed/gfkTfcpWqAY',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=500&auto=format&fit=crop&q=80',
    duration: '1 Hour',
    difficulty: 'Beginner',
    description: 'Fast-paced, high-yield overview of C# and .NET architecture. Understand CLR execution, basic constructs, and classes.',
    keyTopics: ['C# Architecture & CLR', 'Primitive Types', 'Type Conversion', 'Operators & Control Flow', 'Classes & Structs'],
    isFreeVerified: true,
  },

  // --- R PROGRAMMING ---
  {
    id: 'res_r_statquest',
    title: 'StatQuest: R Programming & Statistical Modeling [Josh Starmer]',
    subject: 'R',
    type: 'youtube_playlist',
    provider: 'StatQuest with Josh Starmer',
    url: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUIcdlgu78MnlATeyx4ecEVV',
    embedUrl: 'https://www.youtube.com/embed/6b3nflxP5xQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&auto=format&fit=crop&q=80',
    duration: '25 Videos (6 Hours)',
    difficulty: 'All Levels',
    description: 'Josh Starmer breaks down R programming, data frames, matrices, ggplot2 visualization, linear regression, and logistic regression with intuitive animations and catchy jingles.',
    keyTopics: ['R Vectors & Data Frames', 'Data Visualization with ggplot2', 'Linear Models with lm()', 'Logistic Regression', 'PCA in R', 'Statistical Significance Tests'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_r_fcc',
    title: 'R Programming Tutorial – Learn the Basics of Statistical Computing',
    subject: 'R',
    type: 'youtube_video',
    provider: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=_V8eKsto3Ug',
    embedUrl: 'https://www.youtube.com/embed/_V8eKsto3Ug',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop&q=80',
    duration: '2 Hours 10 Mins',
    difficulty: 'Beginner',
    description: 'Introduction to the R programming language for data analysis and statistics. Covers vectors, factors, data frames, packages, importing datasets, summary statistics, and bar charts.',
    keyTopics: ['R Studio Basics', 'Data Types & Vectors', 'Factors & Categorical Data', 'Data Frames & Tibbles', 'Descriptive Statistics', 'Plotting in Base R'],
    isFreeVerified: true,
  },
  {
    id: 'res_r_harvardx',
    title: 'HarvardX: Data Science: R Basics [Prof. Rafael Irizarry]',
    subject: 'R',
    type: 'free_course',
    provider: 'HarvardX on edX',
    url: 'https://www.edx.org/learn/r-programming/harvard-university-data-science-r-basics',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=500&auto=format&fit=crop&q=80',
    duration: '8-week Course (Free Audit)',
    difficulty: 'Beginner',
    description: 'First course in Harvard’s Data Science professional certificate. Covers R syntax, indexing, data wrangling with dplyr, data visualization with ggplot2, and real-world case studies.',
    keyTopics: ['R Syntax & Basics', 'Data Wrangling with dplyr', 'Vectorization & Indexing', 'ggplot2 Grammar of Graphics', 'Real World Case Studies'],
    isFreeVerified: true,
  },

  // --- DATA STRUCTURES & ALGORITHMS (DSA) ---
  {
    id: 'res_dsa_mit',
    title: 'MIT 6.006: Introduction to Algorithms [Prof. Erik Demaine]',
    subject: 'DSA',
    type: 'free_course',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    embedUrl: 'https://www.youtube.com/embed/ZA-tUyM_y7s',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=500&auto=format&fit=crop&q=80',
    duration: '26 Full Lectures (30 Hours)',
    difficulty: 'Intermediate',
    description: 'World-renowned algorithms course from MIT. Covers asymptotic analysis, sorting (Merge, Heap), binary search trees, AVL trees, hash tables, graph traversals (BFS, DFS), shortest paths (Dijkstra, Bellman-Ford), and dynamic programming.',
    keyTopics: ['Asymptotic Analysis & O(n)', 'Sorting & Priority Queues', 'BST & Balanced AVL Trees', 'Hash Tables & Chaining', 'BFS, DFS & Topological Sort', 'Dynamic Programming Patterns'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_dsa_abdul_bari',
    title: 'Algorithms Masterclass: Design & Analysis [Abdul Bari]',
    subject: 'DSA',
    type: 'youtube_playlist',
    provider: 'Abdul Bari',
    url: 'https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
    duration: '80+ Lectures (25 Hours)',
    difficulty: 'Intermediate',
    description: 'The golden standard algorithms series online. Master divide and conquer, greedy algorithms (Knapsack, Prim, Kruskal, Huffman), dynamic programming (0/1 Knapsack, Floyd-Warshall), and backtracking (N-Queens).',
    keyTopics: ['Divide and Conquer', 'Greedy Method', 'Dynamic Programming', 'Backtracking & Branch-and-Bound', 'NP-Completeness'],
    isFreeVerified: true,
  },

  // --- MATHEMATICS & CALCULUS ---
  {
    id: 'res_math_3b1b',
    title: '3Blue1Brown: Essence of Calculus [Grant Sanderson]',
    subject: 'Mathematics',
    type: 'youtube_playlist',
    provider: '3Blue1Brown',
    url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr',
    embedUrl: 'https://www.youtube.com/embed/WUvTyaaNkzM',
    thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&auto=format&fit=crop&q=80',
    duration: '12 Animated Episodes (3.5 Hours)',
    difficulty: 'All Levels',
    description: 'Grant Sanderson provides profound visual intuition for derivatives, integrals, chain rule, product rule, Taylor series, and limits. Calculus made genuinely intuitive.',
    keyTopics: ['Intuition Behind Derivatives', 'The Chain Rule Visually', 'Integration as Area Accumulation', 'Exponential and e^x', 'Taylor Series Approximations'],
    isFreeVerified: true,
    featured: true,
  },
  {
    id: 'res_math_khan',
    title: 'Khan Academy: Calculus AB & BC Mastery Track',
    subject: 'Mathematics',
    type: 'free_course',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/math/calculus-1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=500&auto=format&fit=crop&q=80',
    duration: 'Full Self-Paced Curriculum',
    difficulty: 'Beginner',
    description: 'Comprehensive interactive curriculum covering limits, differentiation rules, optimization, related rates, Riemann sums, integration techniques, and differential equations with thousands of practice problems.',
    keyTopics: ['Limits & Continuity', 'Differentiation Applications', 'Integration by Parts', 'Differential Equations', 'Parametric & Polar Equations'],
    isFreeVerified: true,
  },
];
